pluginManagement {
    repositories {
        **ARTIFACTORYREPOSITORY**
        maven { url "https://maven.aliyun.com/repository/google" }
        maven { url "https://maven.aliyun.com/repository/central" }
        maven { url "https://maven.aliyun.com/repository/gradle-plugin" }
        maven { url "https://maven.aliyun.com/repository/public" }
        maven { url "https://mirrors.huaweicloud.com/repository/maven/" }
        gradlePluginPortal()
        google()
        mavenCentral()
        maven { url "https://maven.myket.ir" }
        maven { url "https://jitpack.io" }
    }
}

include ':launcher', ':unityLibrary'
**INCLUDES**

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        **ARTIFACTORYREPOSITORY**
        maven { url "https://maven.aliyun.com/repository/google" }
        maven { url "https://maven.aliyun.com/repository/central" }
        maven { url "https://maven.aliyun.com/repository/public" }
        maven { url "https://mirrors.huaweicloud.com/repository/maven/" }
        google()
        mavenCentral()
        maven { url "https://maven.myket.ir" }
        maven { url "https://jitpack.io" }
        flatDir {
            dirs "${project(':unityLibrary').projectDir}/libs"
        }
    }
}
